[package]
name = "gdueiv"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
num = "0.4.1"
serde = { version = "1.0.195", features = ["derive"], optional = true }

[target.'cfg(windows)'.dependencies]
windows = { version = ">=0.52.0", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
] }
